# Email 配置文件
# 用户信息
[user.name]
    zh = "名字"
    en = "Sidney Zhang"

# 邮箱信息 分为 Work 与 Person ，也可添加更多账号信息
# 不同用处的邮箱表需要使用"[email.]"开头
# addr表示邮箱全名；host表示smtp服务器地址；port为服务器端口；password为邮箱密码；tail为邮件签名。
# tail签名仅支持两种方式，一种file添加方式，一种为txt方式，结构均为: [类型，目标]。
# file类型的目标只能为html文件，txt类型目标即为签名文字。
[email.work]
    addr = "sidney@company.com"
    host = "smtp.company.com"
    port = 465
    password = "password"
    tail = ["file","ui.html"]

[email.person]
    addr = "user@user.com"
    host = "smtp.user.com"
    port = 587
    password = "password"
    tail = ["txt","Sidney Zhang"]

[email.aliyun]
    addr = "user@aliyun.com"
    host = "smtp.aliyun.com"
    port = 465
    password = "password"
    tail = ["txt","Sidney Zhang"]